### ISSUE TITLE
gradlew Unresolved reference: godotengine

### ISSUE THREAD

**Issue by ShadowwLol** [cagdasc/godot-location-plugin#2]
### `./gradlew generatePlugin --stacktrace`
Task :locationplugin:compileDebugKotlin FAILED
e: /home/shadoww/godot-location-plugin/locationplugin/src/main/java/com/cacaosd/locationplugin/LocationKotlinPlugin.kt: (27, 12): Unresolved reference: godotengine

**Help compiling would be appreciated!**

**Comment by j-zeppenfeld** [comment]
You need to copy the Godot "aar library for Android plugins" for your version of Godot from https://godotengine.org/download/ to `locationplugin/aars`.

I agree it would be nice if this were mentioned in the README, took me a while to figure out as well.
